name: Terraform LocalStack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install LocalStack
        run: |
          python -m pip install --upgrade pip
          pip install localstack

      - name: Start LocalStack in background
        run: |
          localstack start -d
          sleep 15

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: terraform init terraform

      - name: Terraform Plan
        run: terraform plan -chdir=terraform
