version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  web:
    build:
      context: ../django_app
      dockerfile: ../docker/Dockerfile.web
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - mynet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  mynet:
    driver: overlay

volumes:
  db_data:
