name: CI-CD Pipeline

on:
  push:
    branches:
      - ITA732

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init & apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Fetch terraform outputs for IPs
        id: outputs
        run: |
          cd terraform
          terraform output -json > /tmp/tf_outputs.json
          cat /tmp/tf_outputs.json

      - name: Copy private key to workspace
        uses: actions/upload-artifact@v4
        with:
          name: terraform-key
          path: terraform/terraform-key.pem

      - name: Run Ansible (local runner)
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: ansible/playbook.yml
          inventory: ansible/inventory.ini
          key: terraform/terraform-key.pem
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
